services:
  - type: web
    name: car-price-predictor
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn script:app
