services:
  - type: web
    name: car-price-predictor
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-build-isolation -r requirements.txt
    startCommand: gunicorn script:app
